version: "3.8"

services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile.dev
      args:
        - DOCKER_USER_UID=${DOCKER_USER_UID:-1000}
        - DOCKER_USER_GID=${DOCKER_USER_GID:-1000}
    environment:
      - PYTHONPATH=/workspace/application
      - ENVIRONMENT
      - SECURITY_SECRET_KEY
      - SECURITY_ACCESS_TOKEN_EXPIRE_SECONDS
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_VIRTUAL_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
    working_dir: /workspace/application
    volumes:
      - .:/workspace:rw
