version: "3.8"

services:
  backend-api:
    container_name: backend-api
    build:
      context: ./backend
      args:
        - DOCKER_BACKEND_UID
    volumes:
      - ./backend:/usr/src/app:rw
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
