name: pull-request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up --detach --build --wait
      - run: docker compose exec api ./api/do-lint.sh
      - run: docker compose exec api ./api/do-test.sh
